--DO NOT EDIT THIS FILE. 

UnboxingItems = {}
UnboxingConfig = {}

local count = 1

function addWeaponItem(itemName , weaponName, itemModel, itemChance, itemColor)

	UnboxingItems[count] = {}
	UnboxingItems[count].itemName = itemName
	UnboxingItems[count].Type = "WEAPON"
	UnboxingItems[count].weaponName = weaponName
	UnboxingItems[count].itemModel = weaponModel
	UnboxingItems[count].itemChance = itemChance
	UnboxingItems[count].itemColor = itemColor
	UnboxingItems[count].itemModel = itemModel

	count = count + 1

end

function addPointShopPoints(itemName , pointAmount , itemChance, itemColor)

	UnboxingItems[count] = {}
	UnboxingItems[count].itemName = itemName
	UnboxingItems[count].Type = "POINTS"
	UnboxingItems[count].PointAmount = pointAmount
	UnboxingItems[count].itemChance = itemChance
	UnboxingItems[count].itemColor = itemColor

	count = count + 1


end

function addPointShopItem(itemName , itemClassName , itemModel, itemChance, itemColor)

	UnboxingItems[count] = {}
	UnboxingItems[count].itemName = itemName
	UnboxingItems[count].Type = "PITEM"
	UnboxingItems[count].itemClassName = itemClassName
	UnboxingItems[count].itemModel = itemModel
	UnboxingItems[count].itemChance = itemChance
	UnboxingItems[count].itemColor = itemColor

	count = count + 1


end

function addPointShopTrail(itemName , trailClassName, itemChance, itemColor)

	UnboxingItems[count] = {}
	UnboxingItems[count].itemName = itemName
	UnboxingItems[count].Type = "TRAIL"
	UnboxingItems[count].itemClassName = trailClassName
	UnboxingItems[count].itemChance = itemChance
	UnboxingItems[count].itemColor = itemColor

	count = count + 1


end

function addEntityItem(itemName , entityName, itemModel, itemChance, itemColor)

	UnboxingItems[count] = {}
	UnboxingItems[count].itemName = itemName
	UnboxingItems[count].Type = "ENTITIY"
	UnboxingItems[count].entityName = entityName
	UnboxingItems[count].itemModel = weaponModel
	UnboxingItems[count].itemChance = itemChance
	UnboxingItems[count].itemColor = itemColor
	UnboxingItems[count].itemModel = itemModel

	count = count + 1
	
end

function addMoneyItem(itemName , amount , itemChance , itemColor)

	UnboxingItems[count] = {}
	UnboxingItems[count].itemName = itemName
	UnboxingItems[count].Type = "MONEY"
	UnboxingItems[count].moneyAmount = amount
	UnboxingItems[count].itemChance = itemChance
	UnboxingItems[count].itemColor = itemColor
	UnboxingItems[count].itemModel = "models/props/cs_assault/money.mdl"

	count = count + 1


end

-- 76561198064956670

function addHealthItem(itemName , amount , itemChance , itemColor)

	UnboxingItems[count] = {}
	UnboxingItems[count].itemName = itemName
	UnboxingItems[count].Type = "HEALTH"
	UnboxingItems[count].healAmount = amount
	UnboxingItems[count].itemModel = weaponModel
	UnboxingItems[count].itemChance = itemChance
	UnboxingItems[count].itemColor = itemColor
	UnboxingItems[count].itemModel = "models/items/healthkit.mdl"

	count = count + 1


end